### ISSUE TITLE
Recode launcher with Electron

### ISSUE THREAD

**Issue by FunixG** [FunixG/PacifistaLauncher#7]
Setup project with Electron for UI

**Comment by FunixG** [comment]
Info de @iGameCreep 

J'ai vu hier que tu avais crée (début septembre) une branche sur le PacifistaLauncher qui contient des recherches avec ElectronJS.
J'ai fais qqes recherches et regardé des projets similaires et je comprends un peu le fonctionnement (j'ai pu faire une base qui va jusqu'a la connexion).
En gros, electron transforme des pages web en application (.exe) en gardant NodeJS.
Pour faire un launcher, il faut donc:
L'équivalent d'un site web (HTML,CSS,JS),
De quoi faire une connexion avec Microsoft (app azure, accès APIs...)
Des modules pour lancer le jeu directement (comme minecraft-launcher-core par ex.)
Et éventuellement:
Auto updater (recherche des dernières version et MAJs)
Sauvegarde des comptes (éviter de se reconnecter à chaque fois)

Pour les accès APIs avec Microsoft (depuis la migration des comptes on utilise plus Mojang pour se connecter), il faut (après avoir fait une application Azure et s'y être connecté) remplir un formulaire et attendre une réponse pour qu'ils valident l'accès aux APIs Minecraft (récupérer les infos du joueur depuis le token d'accès Microsoft en gros)
Il y à un launcher open source très complet (j'ai regardé le code pour le comprendre et faire une base) qui existe, le git ici: https://github.com/dscalzi/HeliosLauncher
Voilà tout !

**Comment by iGameCreep** [comment]
Fonctionnement du login avec Microsoft: 1 token Microsoft -> 1 token Xbox Live (XBL) -> 1 autre token Xbox Live (XSTS) -> un token Minecraft (accès API requis).
Wiki pour toute la connexion: https://wiki.vg/Microsoft_Authentication_Scheme
API temporaire de test sur replit: https://replit.com/@GameCreep35/FunixProdDevPcftaLauncherImpl
Application Azure temporaire: PacifistaLauncherDev
Récupérer la tête de l'utilisateur connecté: `https://mc-heads.net/body/${authUser.uuid}/right`

**Comment by iGameCreep** [comment]
Tâches requises (fonctionnalitées):
- [x] Connexion microsoft pour minecraft
- [x] Téléchargement du jeu pour lancer le jeu
- [x] Lancement du jeu avec fabric et les mods qui sont requis pour Pacifista (chat vocal par exemple)
- [ ] Update auto du launcher si besoin
- [x] Vérification et installation de Java
- [ ] Dispo Windows/MacOS (voir build)
- [x] Pouvoir installer et désinstaller le launcher (géré par Electron avec l'installeur)

**Comment by iGameCreep** [comment]
Auto update with electron: https://www.youtube.com/watch?v=oaza9tqCWXg
Dependencies: `electron-updater`
Requires publishing a github version on each update
